### ISSUE TITLE
Add classifiers to setup.py to indicate Python support

### ISSUE THREAD

**Issue by svisser** [seveas/whelk#5]
Based on a code comment it seems this package supports Python 2.4 - 3.4.

If so, would it be possible to add PyPI classifiers in the setup call in setup.py?

This is one of my dependencies that isn't publicly compatible with Python 3.x (though various commits suggest it does indeed work with Python 3.x). In particular the project fails to pass this test here:  https://caniusepython3.com/project/whelk. This should help with automatically discovering dependencies that aren't yet Python 3.x compatible.

**Comment by seveas** [comment]
A story about the best laid plans of mice and men:

- A week after the previous comment I was sent to the US for a week to do recruiting
- The next week I was busy catching up
- Then christmas and newyears
- Then the mrs. fell ill... it seemed
- Then it turned out she's pregnant

So, 4 months and 9 days after the previous comment I finally have time to actually go through these projects and issue releases. Fixed by 34555e0 / 2.5.
